version: '3.1'

services:
    db:
        image: postgres:9.6
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres-data-volume:/var/lib/postgresql/data
    rest:
        image: postgrest/postgrest
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - db
        volumes:
            - ./postgrest/postgrest.conf:/etc/postgrest.conf
    web:
        image: openresty/openresty
        restart: always
        depends_on:
            - rest
        ports:
            - "8080:80"
        volumes:
            - ./openresty/default.conf:/etc/nginx/conf.d/default.conf
    swagger:
        image: swaggerapi/swagger-ui
        restart: always
        ports:
            - "8081:8080"
        depends_on:
            - rest
        expose:
            - "8080"
        environment:
            API_URL: http://rest:3000/

volumes:
    postgres-data-volume:
        external: true
